version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/app/src
    container_name: forward-proxy-node
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    command: npm start
